# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/meital/ClionProjects/Secret-Sharing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/meital/ClionProjects/Secret-Sharing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meital/ClionProjects/Secret-Sharing/CMakeFiles /home/meital/ClionProjects/Secret-Sharing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meital/ClionProjects/Secret-Sharing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Secret_Sharing

# Build rule for target.
Secret_Sharing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Secret_Sharing
.PHONY : Secret_Sharing

# fast build rule for target.
Secret_Sharing/fast:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/build
.PHONY : Secret_Sharing/fast

AES_PRG.o: AES_PRG.cpp.o

.PHONY : AES_PRG.o

# target to build an object file
AES_PRG.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/AES_PRG.cpp.o
.PHONY : AES_PRG.cpp.o

AES_PRG.i: AES_PRG.cpp.i

.PHONY : AES_PRG.i

# target to preprocess a source file
AES_PRG.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/AES_PRG.cpp.i
.PHONY : AES_PRG.cpp.i

AES_PRG.s: AES_PRG.cpp.s

.PHONY : AES_PRG.s

# target to generate assembly for a file
AES_PRG.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/AES_PRG.cpp.s
.PHONY : AES_PRG.cpp.s

ArithmeticCircuit.o: ArithmeticCircuit.cpp.o

.PHONY : ArithmeticCircuit.o

# target to build an object file
ArithmeticCircuit.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ArithmeticCircuit.cpp.o
.PHONY : ArithmeticCircuit.cpp.o

ArithmeticCircuit.i: ArithmeticCircuit.cpp.i

.PHONY : ArithmeticCircuit.i

# target to preprocess a source file
ArithmeticCircuit.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ArithmeticCircuit.cpp.i
.PHONY : ArithmeticCircuit.cpp.i

ArithmeticCircuit.s: ArithmeticCircuit.cpp.s

.PHONY : ArithmeticCircuit.s

# target to generate assembly for a file
ArithmeticCircuit.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ArithmeticCircuit.cpp.s
.PHONY : ArithmeticCircuit.cpp.s

Communication.o: Communication.cpp.o

.PHONY : Communication.o

# target to build an object file
Communication.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/Communication.cpp.o
.PHONY : Communication.cpp.o

Communication.i: Communication.cpp.i

.PHONY : Communication.i

# target to preprocess a source file
Communication.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/Communication.cpp.i
.PHONY : Communication.cpp.i

Communication.s: Communication.cpp.s

.PHONY : Communication.s

# target to generate assembly for a file
Communication.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/Communication.cpp.s
.PHONY : Communication.cpp.s

HIM.o: HIM.cpp.o

.PHONY : HIM.o

# target to build an object file
HIM.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/HIM.cpp.o
.PHONY : HIM.cpp.o

HIM.i: HIM.cpp.i

.PHONY : HIM.i

# target to preprocess a source file
HIM.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/HIM.cpp.i
.PHONY : HIM.cpp.i

HIM.s: HIM.cpp.s

.PHONY : HIM.s

# target to generate assembly for a file
HIM.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/HIM.cpp.s
.PHONY : HIM.cpp.s

MPCCommunication.o: MPCCommunication.cpp.o

.PHONY : MPCCommunication.o

# target to build an object file
MPCCommunication.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/MPCCommunication.cpp.o
.PHONY : MPCCommunication.cpp.o

MPCCommunication.i: MPCCommunication.cpp.i

.PHONY : MPCCommunication.i

# target to preprocess a source file
MPCCommunication.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/MPCCommunication.cpp.i
.PHONY : MPCCommunication.cpp.i

MPCCommunication.s: MPCCommunication.cpp.s

.PHONY : MPCCommunication.s

# target to generate assembly for a file
MPCCommunication.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/MPCCommunication.cpp.s
.PHONY : MPCCommunication.cpp.s

Protocol.o: Protocol.cpp.o

.PHONY : Protocol.o

# target to build an object file
Protocol.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/Protocol.cpp.o
.PHONY : Protocol.cpp.o

Protocol.i: Protocol.cpp.i

.PHONY : Protocol.i

# target to preprocess a source file
Protocol.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/Protocol.cpp.i
.PHONY : Protocol.cpp.i

Protocol.s: Protocol.cpp.s

.PHONY : Protocol.s

# target to generate assembly for a file
Protocol.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/Protocol.cpp.s
.PHONY : Protocol.cpp.s

ProtocolTimer.o: ProtocolTimer.cpp.o

.PHONY : ProtocolTimer.o

# target to build an object file
ProtocolTimer.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ProtocolTimer.cpp.o
.PHONY : ProtocolTimer.cpp.o

ProtocolTimer.i: ProtocolTimer.cpp.i

.PHONY : ProtocolTimer.i

# target to preprocess a source file
ProtocolTimer.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ProtocolTimer.cpp.i
.PHONY : ProtocolTimer.cpp.i

ProtocolTimer.s: ProtocolTimer.cpp.s

.PHONY : ProtocolTimer.s

# target to generate assembly for a file
ProtocolTimer.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ProtocolTimer.cpp.s
.PHONY : ProtocolTimer.cpp.s

TemplateField.o: TemplateField.cpp.o

.PHONY : TemplateField.o

# target to build an object file
TemplateField.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/TemplateField.cpp.o
.PHONY : TemplateField.cpp.o

TemplateField.i: TemplateField.cpp.i

.PHONY : TemplateField.i

# target to preprocess a source file
TemplateField.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/TemplateField.cpp.i
.PHONY : TemplateField.cpp.i

TemplateField.s: TemplateField.cpp.s

.PHONY : TemplateField.s

# target to generate assembly for a file
TemplateField.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/TemplateField.cpp.s
.PHONY : TemplateField.cpp.s

VDM.o: VDM.cpp.o

.PHONY : VDM.o

# target to build an object file
VDM.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/VDM.cpp.o
.PHONY : VDM.cpp.o

VDM.i: VDM.cpp.i

.PHONY : VDM.i

# target to preprocess a source file
VDM.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/VDM.cpp.i
.PHONY : VDM.cpp.i

VDM.s: VDM.cpp.s

.PHONY : VDM.s

# target to generate assembly for a file
VDM.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/VDM.cpp.s
.PHONY : VDM.cpp.s

ZpGMPElement.o: ZpGMPElement.cpp.o

.PHONY : ZpGMPElement.o

# target to build an object file
ZpGMPElement.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ZpGMPElement.cpp.o
.PHONY : ZpGMPElement.cpp.o

ZpGMPElement.i: ZpGMPElement.cpp.i

.PHONY : ZpGMPElement.i

# target to preprocess a source file
ZpGMPElement.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ZpGMPElement.cpp.i
.PHONY : ZpGMPElement.cpp.i

ZpGMPElement.s: ZpGMPElement.cpp.s

.PHONY : ZpGMPElement.s

# target to generate assembly for a file
ZpGMPElement.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ZpGMPElement.cpp.s
.PHONY : ZpGMPElement.cpp.s

ZpMersenneIntElement.o: ZpMersenneIntElement.cpp.o

.PHONY : ZpMersenneIntElement.o

# target to build an object file
ZpMersenneIntElement.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ZpMersenneIntElement.cpp.o
.PHONY : ZpMersenneIntElement.cpp.o

ZpMersenneIntElement.i: ZpMersenneIntElement.cpp.i

.PHONY : ZpMersenneIntElement.i

# target to preprocess a source file
ZpMersenneIntElement.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ZpMersenneIntElement.cpp.i
.PHONY : ZpMersenneIntElement.cpp.i

ZpMersenneIntElement.s: ZpMersenneIntElement.cpp.s

.PHONY : ZpMersenneIntElement.s

# target to generate assembly for a file
ZpMersenneIntElement.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/ZpMersenneIntElement.cpp.s
.PHONY : ZpMersenneIntElement.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Secret_Sharing.dir/build.make CMakeFiles/Secret_Sharing.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Secret_Sharing"
	@echo "... AES_PRG.o"
	@echo "... AES_PRG.i"
	@echo "... AES_PRG.s"
	@echo "... ArithmeticCircuit.o"
	@echo "... ArithmeticCircuit.i"
	@echo "... ArithmeticCircuit.s"
	@echo "... Communication.o"
	@echo "... Communication.i"
	@echo "... Communication.s"
	@echo "... HIM.o"
	@echo "... HIM.i"
	@echo "... HIM.s"
	@echo "... MPCCommunication.o"
	@echo "... MPCCommunication.i"
	@echo "... MPCCommunication.s"
	@echo "... Protocol.o"
	@echo "... Protocol.i"
	@echo "... Protocol.s"
	@echo "... ProtocolTimer.o"
	@echo "... ProtocolTimer.i"
	@echo "... ProtocolTimer.s"
	@echo "... TemplateField.o"
	@echo "... TemplateField.i"
	@echo "... TemplateField.s"
	@echo "... VDM.o"
	@echo "... VDM.i"
	@echo "... VDM.s"
	@echo "... ZpGMPElement.o"
	@echo "... ZpGMPElement.i"
	@echo "... ZpGMPElement.s"
	@echo "... ZpMersenneIntElement.o"
	@echo "... ZpMersenneIntElement.i"
	@echo "... ZpMersenneIntElement.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

